export {Header} from "./Header/Header"
export {Logo} from "./Logo/Logo"
export {LogoDark} from "./Logo/LogoDark"
export {Navbar} from "./Navbar/Navbar"
export {LightButton} from "./LightButton/LightButton"
export {Photo} from "./Photo/Photo"
export {Intro} from "./Intro/Intro"
export {AboutMe} from "./AboutMe/AboutMe"
export {ProgrammingLanguagesImg} from "./ProgrammingLanguagesImg/ProgrammingLanguagesImg"
export {Experience} from "./Experience/Experience"
export {Projects} from "./Projects/Projects"
export {Contact} from "./Contact/Contact"
// export {FooterImg} from "./FooterImg/FooterImg"
// export {FooterDarkImg} from "./FooterDarkImg/FooterDarkImg"
// export {Footer} from "./Footer/Footer"